# Change these first
owner: happecharger # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - Damha Ahn
  - Jinwook Kim
  - Namju Lee
  - Jaewon Noh
  - Hyobum Moon

sites:
  - name: website
    url: https://www.happecharger.com
  - name: application
    url: https://app2.happecharger.com
  - name: cms
    url: https://cms.happecharger.com
  - name: evc
    url: http://adm.kevcs.com
    port: 28088
  - name: acc
    url: https://acc.happecharger.com/
  - name: legacy mobile
    url: https://m.happecharger.com/mobile/main.do
  - name: legacy website
    url: https://cs.happecharger.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.kevcs.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Web Status"
  introMessage: 서버 상태 확인
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
