# Change these first
owner: happecharger # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - Damha Ahn
  - Jinwook Kim
  - Namju Lee
  - Jaewon Noh
  - Hyobum Moon

sites:
  - name: ActiveMQ
    url: http://10.20.59.4:8161/
    headers:
      - "Authorization: Basic YWRtaW46YWRtaW4="
  - name: 해피차저 웹사이트
    url: https://www.happecharger.com
  - name: 해피차저 앱
    url: https://app2.happecharger.com
  - name: 해피차저 CMS
    url: https://cms.happecharger.com
  - name: EVC (충전관리시스템)
    url: http://adm.kevcs.com
  - name: ACC (정산관리시스템)
    url: https://acc.happecharger.com/
  - name: ADM (구.충전관리시스템)
    url: http://adm.happecharger.com/
  - name: ASSEMBLE (메시지관리시스템)
    url: http://noti.kevcs.co.kr:7200/
  - name: ESOL (API시스템)
    url: https://api2.happecharger.com/
  - name: 비회원QR
    url: http://211.253.17.41:28088/
  - name: 기존 해피차저 모바일웹
    url: https://m.happecharger.com/
  - name: 기존 해피차저 웹사이트
    url: https://cs.happecharger.com
  - name: 개발 (Jenkins)
    url: http://211.253.17.45:8085/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.kevcs.com
  # baseUrl: /upptime
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  robotsText: "User-agent: * \n Disallow: /"
  name: 한국전기차충전서비스
  introTitle: "해피차저 서비스"
  introMessage: 서버 상태
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: 활성 이슈
  allSystemsOperational: 전체 시스템이 작동 중 입니다.
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: 발생일시
  incidentClosedAt: 종료일시
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← 전체이슈로 돌아가기
  pastIncidents: 지난 이슈
  pastIncidentsResolved: 해결이슈 ($POSTS 게시물/$MINUTES 분)
  liveStatus: 활성 상태
  overallUptime: "전체가동시간: $UPTIME"
  overallUptimeTitle: 전체가동시간
  averageResponseTime: "평균응답시간: $TIMEms"
  averageResponseTimeTitle: 평균응답시간
  sevelDayResponseTime: 7일 응답시간
  responseTimeMs: 응답시간(ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: 한도 초과
  rateLimitExceededIntro: 한 시간에 가용 할 수 있는 요청 수를 초과했으므로 이 웹사이트에 다시 액세스하기 전까지 기다려야 합니다. 또는 GitHub 개인 엑세스 토큰을 추가하여 이 웹사이트를 계속 사용할 수 있습니다.
  rateLimitExceededWhatDoesErrorMean: 이 오류는 무엇을 의미하나요?
  rateLimitExceededErrorMeaning: 이 웹사이트는 GitHub API를 사용하여 당사 웹사이트의 상태를 실시간으로 액세스합니다. 기본적으로 GitHub는 각 IP 주소에 시간당 60개의 요청을 허용합니다.
  rateLimitExceededErrorHowCanFix: 어떻게 고칠 수 있나요?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: 개인 엑세스 토큰을 생성하는 방법
  rateLimitExceededHasSet: 개인 엑세스 토큰이 설정되었습니다.
  rateLimitExceededRemoveToken: 토큰 제거
  rateLimitExceededGitHubPAT: GitHub 개인 엑세스 토큰
  rateLimitExceededCopyPastePAT: 토큰을 복사하여 붙여넣으세요.
  rateLimitExceededSaveToken: 토큰 저장
  errorTitle: 오류 발생
  errorIntro: 최신 상태 세부 정보를 가져오는 중 오류가 발생했습니다.
  errorText: 잠시 후에 다시 시도할 수 있습니다.
  errorHome: 홈
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION 분
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24시간
  duration7D: 7일
  duration30D: 30일
  duration1Y: 1년
  durationAll: 전체
  locale: ko-KR      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
