# Change these first
owner: happecharger # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - Damha Ahn
  - Jinwook Kim
  - Namju Lee
  - Jaewon Noh
  - Hyobum Moon

sites:
  - name: Happecharger Website
    url: https://www.happecharger.com
  - name: Happecharger Hybrid Application Site 2
    url: https://app2.happecharger.com
  - name: Happecharger Hybrid Application Site 1
    url: https://app.happecharger.com
  - name: Legacy Mobile Site
    url: https://m.happecharger.com/mobile/main.do

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Web Status"
  introMessage: 서버 상태 확인
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
