# Change these first
owner: happecharger # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - Damha Ahn
  - Jinwook Kim
  - Namju Lee
  - Jaewon Noh
  - Hyobum Moon

sites:
  - name: website
    url: https://www.happecharger.com
  - name: application
    url: https://app2.happecharger.com
  - name: cms
    url: https://cms.happecharger.com
  - name: evc
    url: http://adm.kevcs.com
  - name: acc
    url: https://acc.happecharger.com/
  - name: legacy mobile
    url: https://m.happecharger.com/
  - name: legacy website
    url: https://cs.happecharger.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.kevcs.com
  # baseUrl: /upptime
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  robotsText: "User-agent: * \n Disallow: /"
  name: 한국전기차충전서비스
  introTitle: "해피차저 서비스"
  introMessage: 전체 상태
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems are operational
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← 전체이슈로 돌아가기
  pastIncidents: 지난 이슈
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: 세부 상태
  overallUptime: "전체가동시간: $UPTIME"
  overallUptimeTitle: 전체가동시간
  averageResponseTime: "평균응답시간: $TIMEms"
  averageResponseTimeTitle: 평균응답시간
  sevelDayResponseTime: 7일 응답시간
  responseTimeMs: 응답시간(ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION 분
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24시간
  duration7D: 7일
  duration30D: 30일
  duration1Y: 1년
  durationAll: 전체
  locale: ko-KR      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
